Add feature to support line number args
kyoh86/vim-editerm pull request #20
Opened 2021-01-09 14:29 UTC by shun095

This PR adds feature to support following command
```
$EDITOR +10 file.txt
```

2021-01-17 09:15 UTC, kyoh86 commented on plugin/tvim
> +    opts="${opt:-} ${file}"
```suggestion
    opts="${opts:-} ${file}"
```

2021-01-17 09:15 UTC, kyoh86 requested changes
nits

2021-01-21 13:09 UTC, shun095 commented
Sorry, thank you very much for your reviewing!

2021-01-22 03:29 UTC, kyoh86 commented on autoload/editerm.vim
> +function! editerm#open(command, lockfile, filename, options)
```suggestion
function! editerm#open(command, lockfile='', filename='', options='')
```

2021-01-22 03:30 UTC, kyoh86 commented on plugin/editerm.vim
> +    call editerm#open(a:arglist[0], a:arglist[1], a:arglist[2], a:arglist[3])
```suggestion
  if len(a:arglist) <= 4
    call call('editerm#open', a:arglist)
```

2021-01-22 03:30 UTC, kyoh86 commented on plugin/tdrop
> +    echo -e "\033]51;[\"call\", \"Tapi_EditermEditFile\", [\"${VIM_EDITERM_OPENER}\", \"\", \"\", \"\"]]\007"
```suggestion
    echo -e "\033]51;[\"call\", \"Tapi_EditermEditFile\", [\"${VIM_EDITERM_OPENER}\"]]\007"
```

2021-01-22 03:31 UTC, kyoh86 commented on plugin/tdrop
> +  echo -e "\033]51;[\"call\", \"Tapi_EditermEditFile\", [\"${VIM_EDITERM_OPENER}\", \"\", \"$file\", \"\"]]\007"
```suggestion
  echo -e "\033]51;[\"call\", \"Tapi_EditermEditFile\", [\"${VIM_EDITERM_OPENER}\", \"\", \"$file\"]]\007"
```

2021-01-22 03:31 UTC, kyoh86 approved these changes
LGTM with nits

2021-01-22 03:32 UTC, merged